"""Pydantic schemas module."""

from app.schemas.analysis import (
    AnalysisRunResponse,
    ClassMetricsListResponse,
    ClassMetricsResponse,
    CodeSmellListResponse,
    CodeSmellResponse,
    FileMetricsListResponse,
    FileMetricsResponse,
    FunctionMetricsListResponse,
    FunctionMetricsResponse,
    RepositoryMetricsResponse,
)
from app.schemas.architecture import (
    ArchitectureAnalysisResponse,
    ArchitectureLayerResponse,
    ArchitectureViolationResponse,
    DependencyGraphResponse,
    DetectedPatternListResponse,
    DetectedPatternResponse,
    FrameworkDetectionResponse,
    TechnologyStackResponse,
)
from app.schemas.health import HealthResponse
from app.schemas.maintainability import (
    CiAnalysisResponse,
    CommitAnalysisResponse,
    CommunityAnalysisResponse,
    DocumentationAnalysisResponse,
    GitHistoryAnalysisResponse,
    MaintainabilityMetricsResponse,
    ReadmeAnalysisResponse,
    ReleaseAnalysisResponse,
    RepositoryHealthResponse,
    TestingAnalysisResponse,
)
from app.schemas.repository import (
    FileIndexResponse,
    RepositoryCreate,
    RepositoryListResponse,
    RepositoryResponse,
)
from app.schemas.security import (
    AuthenticationFindingListResponse,
    AuthenticationFindingResponse,
    AuthorizationFindingListResponse,
    AuthorizationFindingResponse,
    ConfigurationFindingListResponse,
    ConfigurationFindingResponse,
    DependencyFindingListResponse,
    DependencyFindingResponse,
    SecretFindingListResponse,
    SecretFindingResponse,
    SecurityAnalysisResponse,
    SecurityFindingListResponse,
    SecurityFindingResponse,
)
from app.schemas.version import VersionResponse

__all__ = [
    "HealthResponse",
    "VersionResponse",
    "RepositoryCreate",
    "RepositoryResponse",
    "RepositoryListResponse",
    "FileIndexResponse",
    "AnalysisRunResponse",
    "RepositoryMetricsResponse",
    "FileMetricsResponse",
    "FileMetricsListResponse",
    "FunctionMetricsResponse",
    "FunctionMetricsListResponse",
    "ClassMetricsResponse",
    "ClassMetricsListResponse",
    "CodeSmellResponse",
    "CodeSmellListResponse",
    "ArchitectureAnalysisResponse",
    "ArchitectureLayerResponse",
    "ArchitectureViolationResponse",
    "DetectedPatternResponse",
    "DetectedPatternListResponse",
    "DependencyGraphResponse",
    "FrameworkDetectionResponse",
    "TechnologyStackResponse",
    "SecurityAnalysisResponse",
    "SecurityFindingResponse",
    "SecurityFindingListResponse",
    "SecretFindingResponse",
    "SecretFindingListResponse",
    "DependencyFindingResponse",
    "DependencyFindingListResponse",
    "ConfigurationFindingResponse",
    "ConfigurationFindingListResponse",
    "AuthenticationFindingResponse",
    "AuthenticationFindingListResponse",
    "AuthorizationFindingResponse",
    "AuthorizationFindingListResponse",
    "MaintainabilityMetricsResponse",
    "DocumentationAnalysisResponse",
    "ReadmeAnalysisResponse",
    "TestingAnalysisResponse",
    "GitHistoryAnalysisResponse",
    "CommitAnalysisResponse",
    "ReleaseAnalysisResponse",
    "CiAnalysisResponse",
    "CommunityAnalysisResponse",
    "RepositoryHealthResponse",
]
