"""Base import module for Alembic database migrations."""

from app.models.analysis import (
    AnalysisRun,
    ClassMetrics,
    CodeSmell,
    DuplicateFile,
    DuplicateGroup,
    FileMetrics,
    FunctionMetrics,
    RepositoryMetrics,
)
from app.models.architecture import (
    ArchitectureAnalysis,
    ArchitectureLayer,
    ArchitectureRecommendationPlaceholder,
    ArchitectureViolation,
    DependencyEdge,
    DependencyGraph,
    DependencyNode,
    DetectedPattern,
    FrameworkDetection,
    TechnologyStack,
)
from app.models.base import Base
from app.models.repository import Repository, RepositoryFileIndex
from app.models.security import (
    AuthenticationFinding,
    AuthorizationFinding,
    ConfigurationFinding,
    DependencyFinding,
    SecretFinding,
    SecurityAnalysis,
    SecurityFinding,
    SecurityReference,
    SecurityRule,
    SecuritySummary,
)

__all__ = [
    "Base",
    "Repository",
    "RepositoryFileIndex",
    "AnalysisRun",
    "RepositoryMetrics",
    "FileMetrics",
    "FunctionMetrics",
    "ClassMetrics",
    "DuplicateGroup",
    "DuplicateFile",
    "CodeSmell",
    "ArchitectureAnalysis",
    "ArchitectureLayer",
    "ArchitectureViolation",
    "DetectedPattern",
    "DependencyGraph",
    "DependencyNode",
    "DependencyEdge",
    "FrameworkDetection",
    "TechnologyStack",
    "ArchitectureRecommendationPlaceholder",
    "SecurityAnalysis",
    "SecurityFinding",
    "SecretFinding",
    "DependencyFinding",
    "ConfigurationFinding",
    "AuthenticationFinding",
    "AuthorizationFinding",
    "SecurityRule",
    "SecurityReference",
    "SecuritySummary",
]
